# coding: utf-8

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cryptogate.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_detailed_transaction(self) -> None:
        """Test case for create_detailed_transaction

        Create an itemized transaction (Professional/Enterprise plans)
        """
        pass

    def test_create_transaction(self) -> None:
        """Test case for create_transaction

        Create a payment transaction
        """
        pass

    def test_get_transaction(self) -> None:
        """Test case for get_transaction

        Retrieve a single transaction
        """
        pass

    def test_list_transactions(self) -> None:
        """Test case for list_transactions

        List the merchant's transactions (newest first)
        """
        pass


if __name__ == '__main__':
    unittest.main()
