# coding: utf-8

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cryptogate.models.get_account200_response import GetAccount200Response

class TestGetAccount200Response(unittest.TestCase):
    """GetAccount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccount200Response:
        """Test GetAccount200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccount200Response`
        """
        model = GetAccount200Response()
        if include_optional:
            return GetAccount200Response(
                success = None,
                data = cryptogate.models.account.Account(
                    plan = cryptogate.models.account_plan.Account_plan(
                        tier = 'starter', 
                        billing_cycle = '', 
                        auto_renewal = True, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    usage = cryptogate.models.account_usage.Account_usage(
                        monthly_transactions_used = 56, 
                        monthly_transaction_limit = 56, 
                        overage_cost_per_tx = 1.337, ), 
                    limits = cryptogate.models.account_limits.Account_limits(
                        api_rate_limit_per_minute = 56, 
                        api_rate_limit_per_hour = 56, 
                        webhook_support = True, ), )
            )
        else:
            return GetAccount200Response(
                success = None,
                data = cryptogate.models.account.Account(
                    plan = cryptogate.models.account_plan.Account_plan(
                        tier = 'starter', 
                        billing_cycle = '', 
                        auto_renewal = True, 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    usage = cryptogate.models.account_usage.Account_usage(
                        monthly_transactions_used = 56, 
                        monthly_transaction_limit = 56, 
                        overage_cost_per_tx = 1.337, ), 
                    limits = cryptogate.models.account_limits.Account_limits(
                        api_rate_limit_per_minute = 56, 
                        api_rate_limit_per_hour = 56, 
                        webhook_support = True, ), ),
        )
        """

    def testGetAccount200Response(self):
        """Test GetAccount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
