# coding: utf-8

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cryptogate.models.get_stats200_response import GetStats200Response

class TestGetStats200Response(unittest.TestCase):
    """GetStats200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStats200Response:
        """Test GetStats200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStats200Response`
        """
        model = GetStats200Response()
        if include_optional:
            return GetStats200Response(
                success = None,
                data = cryptogate.models.get_stats_200_response_data.getStats_200_response_data(
                    total_transactions = 56, 
                    monthly_transactions = 56, 
                    total_volume_fiat = 1.337, 
                    unique_customers = 56, )
            )
        else:
            return GetStats200Response(
                success = None,
                data = cryptogate.models.get_stats_200_response_data.getStats_200_response_data(
                    total_transactions = 56, 
                    monthly_transactions = 56, 
                    total_volume_fiat = 1.337, 
                    unique_customers = 56, ),
        )
        """

    def testGetStats200Response(self):
        """Test GetStats200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
