# coding: utf-8

# flake8: noqa

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# import apis into sdk package
from cryptogate.api.account_api import AccountApi
from cryptogate.api.billing_api import BillingApi
from cryptogate.api.market_data_api import MarketDataApi
from cryptogate.api.system_api import SystemApi
from cryptogate.api.transactions_api import TransactionsApi

# import ApiClient
from cryptogate.api_response import ApiResponse
from cryptogate.api_client import ApiClient
from cryptogate.configuration import Configuration
from cryptogate.exceptions import OpenApiException
from cryptogate.exceptions import ApiTypeError
from cryptogate.exceptions import ApiValueError
from cryptogate.exceptions import ApiKeyError
from cryptogate.exceptions import ApiAttributeError
from cryptogate.exceptions import ApiException

# import models into sdk package
from cryptogate.models.account import Account
from cryptogate.models.account_limits import AccountLimits
from cryptogate.models.account_plan import AccountPlan
from cryptogate.models.account_usage import AccountUsage
from cryptogate.models.balance import Balance
from cryptogate.models.create_billing_checkout_request import CreateBillingCheckoutRequest
from cryptogate.models.create_detailed_transaction_request import CreateDetailedTransactionRequest
from cryptogate.models.create_transaction_request import CreateTransactionRequest
from cryptogate.models.crypto_symbol import CryptoSymbol
from cryptogate.models.cryptocurrency import Cryptocurrency
from cryptogate.models.error import Error
from cryptogate.models.fiat_currency import FiatCurrency
from cryptogate.models.get_account200_response import GetAccount200Response
from cryptogate.models.get_health200_response import GetHealth200Response
from cryptogate.models.get_prices200_response import GetPrices200Response
from cryptogate.models.get_prices200_response_data import GetPrices200ResponseData
from cryptogate.models.get_stats200_response import GetStats200Response
from cryptogate.models.get_stats200_response_data import GetStats200ResponseData
from cryptogate.models.inline_object import InlineObject
from cryptogate.models.inline_object_all_of_existing_transaction import InlineObjectAllOfExistingTransaction
from cryptogate.models.invoice import Invoice
from cryptogate.models.line_item import LineItem
from cryptogate.models.list_balances200_response import ListBalances200Response
from cryptogate.models.list_balances200_response_data import ListBalances200ResponseData
from cryptogate.models.list_cryptocurrencies200_response import ListCryptocurrencies200Response
from cryptogate.models.list_cryptocurrencies200_response_data import ListCryptocurrencies200ResponseData
from cryptogate.models.list_invoices200_response import ListInvoices200Response
from cryptogate.models.list_invoices200_response_data import ListInvoices200ResponseData
from cryptogate.models.list_plans200_response import ListPlans200Response
from cryptogate.models.list_plans200_response_data import ListPlans200ResponseData
from cryptogate.models.list_transactions200_response import ListTransactions200Response
from cryptogate.models.list_transactions200_response_data import ListTransactions200ResponseData
from cryptogate.models.pagination import Pagination
from cryptogate.models.payment_split import PaymentSplit
from cryptogate.models.plan import Plan
from cryptogate.models.plan_tier import PlanTier
from cryptogate.models.transaction import Transaction
from cryptogate.models.transaction_envelope import TransactionEnvelope
from cryptogate.models.transaction_status import TransactionStatus
from cryptogate.models.webhook_payload import WebhookPayload
