# coding: utf-8

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…` for live, or `sk_test_…` for test mode — same base URL). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cryptogate.models.crypto_symbol import CryptoSymbol
from cryptogate.models.fiat_currency import FiatCurrency
from cryptogate.models.line_item import LineItem
from cryptogate.models.payment_split import PaymentSplit
from cryptogate.models.transaction_status import TransactionStatus
from typing import Optional, Set
from typing_extensions import Self

class Transaction(BaseModel):
    """
    The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
    """ # noqa: E501
    transaction_id: StrictStr
    status: TransactionStatus
    type: Optional[StrictStr] = None
    crypto: CryptoSymbol
    deposit_address: Optional[StrictStr] = None
    amount_crypto: Optional[Union[StrictFloat, StrictInt]] = None
    amount_fiat: Union[StrictFloat, StrictInt]
    amount_usd: Union[StrictFloat, StrictInt]
    amount_paid: Optional[Union[StrictFloat, StrictInt]] = None
    amount_remaining: Optional[Union[StrictFloat, StrictInt]] = None
    currency_fiat: FiatCurrency
    fiat_to_usd_rate: Optional[Union[StrictFloat, StrictInt]] = None
    exchange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="USD per unit of crypto, locked at creation.")
    confirmations_required: Optional[StrictInt] = None
    payment_url: Optional[StrictStr] = None
    order_id: Optional[StrictStr] = None
    customer_email: Optional[StrictStr] = None
    items: Optional[List[LineItem]] = None
    payments: Optional[List[PaymentSplit]] = Field(default=None, description="On-chain payments detected toward this transaction.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).")
    success_url: Optional[StrictStr] = None
    cancel_url: Optional[StrictStr] = None
    created_at: datetime
    updated_at: Optional[datetime] = None
    expires_at: datetime
    __properties: ClassVar[List[str]] = ["transaction_id", "status", "type", "crypto", "deposit_address", "amount_crypto", "amount_fiat", "amount_usd", "amount_paid", "amount_remaining", "currency_fiat", "fiat_to_usd_rate", "exchange_rate", "confirmations_required", "payment_url", "order_id", "customer_email", "items", "payments", "metadata", "success_url", "cancel_url", "created_at", "updated_at", "expires_at"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['basic', 'detailed']):
            raise ValueError("must be one of enum values ('basic', 'detailed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Transaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item_payments in self.payments:
                if _item_payments:
                    _items.append(_item_payments.to_dict())
            _dict['payments'] = _items
        # set to None if order_id (nullable) is None
        # and model_fields_set contains the field
        if self.order_id is None and "order_id" in self.model_fields_set:
            _dict['order_id'] = None

        # set to None if customer_email (nullable) is None
        # and model_fields_set contains the field
        if self.customer_email is None and "customer_email" in self.model_fields_set:
            _dict['customer_email'] = None

        # set to None if items (nullable) is None
        # and model_fields_set contains the field
        if self.items is None and "items" in self.model_fields_set:
            _dict['items'] = None

        # set to None if success_url (nullable) is None
        # and model_fields_set contains the field
        if self.success_url is None and "success_url" in self.model_fields_set:
            _dict['success_url'] = None

        # set to None if cancel_url (nullable) is None
        # and model_fields_set contains the field
        if self.cancel_url is None and "cancel_url" in self.model_fields_set:
            _dict['cancel_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Transaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transaction_id": obj.get("transaction_id"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "crypto": obj.get("crypto"),
            "deposit_address": obj.get("deposit_address"),
            "amount_crypto": obj.get("amount_crypto"),
            "amount_fiat": obj.get("amount_fiat"),
            "amount_usd": obj.get("amount_usd"),
            "amount_paid": obj.get("amount_paid"),
            "amount_remaining": obj.get("amount_remaining"),
            "currency_fiat": obj.get("currency_fiat") if obj.get("currency_fiat") is not None else FiatCurrency.USD,
            "fiat_to_usd_rate": obj.get("fiat_to_usd_rate"),
            "exchange_rate": obj.get("exchange_rate"),
            "confirmations_required": obj.get("confirmations_required"),
            "payment_url": obj.get("payment_url"),
            "order_id": obj.get("order_id"),
            "customer_email": obj.get("customer_email"),
            "items": [LineItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "payments": [PaymentSplit.from_dict(_item) for _item in obj["payments"]] if obj.get("payments") is not None else None,
            "metadata": obj.get("metadata"),
            "success_url": obj.get("success_url"),
            "cancel_url": obj.get("cancel_url"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


