# coding: utf-8

"""
    CryptoGate API

    Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan's monthly transaction quota (not the request rate). 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cryptogate.models.crypto_symbol import CryptoSymbol
from cryptogate.models.fiat_currency import FiatCurrency
from cryptogate.models.transaction_status import TransactionStatus
from typing import Optional, Set
from typing_extensions import Self

class WebhookPayload(BaseModel):
    """
    Payment-event payload. AMOUNTS ARE STRINGS (e.g. \"100.00\", \"0.00109462\") to preserve decimal precision — parse before arithmetic. 
    """ # noqa: E501
    event: StrictStr
    timestamp: datetime
    transaction_id: StrictStr
    status: TransactionStatus
    currency_crypto: Optional[CryptoSymbol] = None
    currency_fiat: Optional[FiatCurrency] = FiatCurrency.USD
    amount_fiat: Optional[StrictStr] = Field(default=None, description="Decimal string.")
    amount_usd: Optional[StrictStr] = Field(default=None, description="Decimal string.")
    amount_crypto: Optional[StrictStr] = Field(default=None, description="Decimal string.")
    order_id: Optional[StrictStr] = None
    receipt_url: Optional[StrictStr] = Field(default=None, description="Present on completed/overpaid.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).")
    __properties: ClassVar[List[str]] = ["event", "timestamp", "transaction_id", "status", "currency_crypto", "currency_fiat", "amount_fiat", "amount_usd", "amount_crypto", "order_id", "receipt_url", "metadata"]

    @field_validator('event')
    def event_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['payment.created', 'payment.pending', 'payment.completed', 'payment.overpaid', 'payment.partial', 'payment.expired', 'payment.failed']):
            raise ValueError("must be one of enum values ('payment.created', 'payment.pending', 'payment.completed', 'payment.overpaid', 'payment.partial', 'payment.expired', 'payment.failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if order_id (nullable) is None
        # and model_fields_set contains the field
        if self.order_id is None and "order_id" in self.model_fields_set:
            _dict['order_id'] = None

        # set to None if receipt_url (nullable) is None
        # and model_fields_set contains the field
        if self.receipt_url is None and "receipt_url" in self.model_fields_set:
            _dict['receipt_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event": obj.get("event"),
            "timestamp": obj.get("timestamp"),
            "transaction_id": obj.get("transaction_id"),
            "status": obj.get("status"),
            "currency_crypto": obj.get("currency_crypto"),
            "currency_fiat": obj.get("currency_fiat") if obj.get("currency_fiat") is not None else FiatCurrency.USD,
            "amount_fiat": obj.get("amount_fiat"),
            "amount_usd": obj.get("amount_usd"),
            "amount_crypto": obj.get("amount_crypto"),
            "order_id": obj.get("order_id"),
            "receipt_url": obj.get("receipt_url"),
            "metadata": obj.get("metadata")
        })
        return _obj


